# Generated by Django 4.0.4 on 2022-05-15 03:54

import core.models.home
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesmodel',
            old_name='img',
            new_name='img_2',
        ),
        migrations.RenameField(
            model_name='servicesmodel',
            old_name='title',
            new_name='title_2',
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.home.upload_location),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.home.upload_location),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.home.upload_location),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='img_5',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.home.upload_location),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='img_6',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.home.upload_location),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='title_1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='title_3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='title_4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='title_5',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='title_6',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
