# Generated by Django 3.2.13 on 2022-05-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_img_servicesmodel_img_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('body1', models.TextField()),
                ('title2', models.CharField(max_length=255)),
                ('body2', models.TextField()),
                ('pochta', models.EmailField(max_length=254)),
            ],
        ),
    ]
