# Generated by Django 4.0.4 on 2022-05-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_img_servicesmodel_img_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsmodel',
            name='numbers_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statsmodel',
            name='numbers_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statsmodel',
            name='title_1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statsmodel',
            name='title_2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
