# Generated by Django 4.0.4 on 2022-05-15 20:29

import core.models.home
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_statsmodel_numbers_1_statsmodel_numbers_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='body_1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='body_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='body_3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='body_4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='body_5',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.home.upload_location),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.home.upload_location),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.home.upload_location),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.home.upload_location),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='img_5',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.home.upload_location),
        ),
    ]
