# Generated by Django 4.0.4 on 2022-05-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_portfoliomodel_commit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliomodel',
            old_name='img_1',
            new_name='imge',
        ),
    ]
