# Generated by Django 4.0.4 on 2022-05-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_img_1_portfoliomodel_imge'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
